Address: ':8080'
BaseDir: '.'
FileMode: 0644 # expected to be octal
#LogFilePath: '/some/log/file.log' # STDOUT if blank
Tokens:
  - 'superSecretToken'
  - 'someOtherEquallySuperSecretToken'
PathMode: 0755 # expected to be octal